### ISSUE TITLE
Human models not complying as expected

### ISSUE THREAD

**Issue by PedroMaia21** [PedroMaia21/PSR_TP3#22]
The male and female models are not behaving as they should, and should be replaced accordingly

**Comment by MarsRodrigues** [comment]
I'm going to replace the models for different ones

**Comment by MarsRodrigues** [comment]
Could you check if they are behaving as expected? I believe everything is ok. This model is the latest, hope that fixes it.

**Comment by PedroMaia21** [comment]
Going to do a test run right now

**Comment by PedroMaia21** [comment]
Unfortunately, the models have the same issue.
Maybe we should check any other repository or model database to found some that comply better.

If they still have some issues, we can just define them as static and let it be like that

**Comment by MarsRodrigues** [comment]
I'm not finding any other good models. Found a person standing and a person walking in [here](https://github.com/osrf/gazebo_models.git). If we don't find other alternatives we could give this a try. I'll be working on finding better models. Meanwhile, could you describe better what you think it's not working? I will also see if maybe I can fix this models, by changing slightly some parameters.

**Comment by PedroMaia21** [comment]
![Screenshot from 2024-01-29 13-38-50](https://github.com/PedroMaia21/PSR_TP3/assets/116599734/7a89ee94-2c8e-4f9f-aaca-58d6ba6e3e1d)
This is what is happening, the body parts are separating from the clothes
If you dont find anything, we will leave it as static. That way it also does not falls down

**Comment by MarsRodrigues** [comment]
I didn't find anything and there's not much time left so I'll configure it as static and mark this task as done.
It's not ideal but I think it's the best approach at this time.
