### ISSUE TITLE
Object Identification and Tracking

### ISSUE THREAD

**Issue by MarsRodrigues** [PedroMaia21/PSR_TP3#8]
I haven't found much information on the YOLO method yet, but I'm reading a [thesis](https://webthesis.biblio.polito.it/12461/1/tesi.pdf) (page 64 goes into more detail about ROS and Gazebo) that seems to have useful information. 

I'm going to try to work on the code around identifying objects in the plane in which the robot walks.
 Then I'll try to explore identification on the table and the bed, for example.

**Comment by PedroMaia21** [comment]
Right now haven't had much luck with the implementation of the perception of objects. Even though it is (kind of) working, its pretty slow in showing the results even when the processing of the image only takes a couple of seconds. It could be related with the lack of RAM and CPU power my laptop has to run both gazebo darknet and Rviz. Right now, my goal is to implement it, but keeping it in the background to save resources and only be called when needed.

**Comment by PedroMaia21** [comment]
I believe everything in this subject its now completed and ready to be added in #10
