### ISSUE TITLE
Object spawing in the howse

### ISSUE THREAD

**Issue by PedroMaia21** [PedroMaia21/PSR_TP3#9]
Its mandatory to create a script to spawn objects in the house. An example can be found in [this PSR repository](https://github.com/miguelriemoliveira/psr_23-24/blob/6b42eaa7925f1c7114a75c8d1acc46236f4a5613/Parte12/robutler_bringup_23-24/scripts/spawn_object.py) because it was explained in classes how to do it

**Comment by PedroMaia21** [comment]
Gonna start working on this now

**Comment by PedroMaia21** [comment]
Right now, been looking for laptop models to spawn

**Comment by MarsRodrigues** [comment]
> Its mandatory to create a script to spawn objects in the house. An example can be found in [this PSR repository](https://github.com/miguelriemoliveira/psr_23-24/blob/6b42eaa7925f1c7114a75c8d1acc46236f4a5613/Parte12/robutler_bringup_23-24/scripts/spawn_object.py) because it was explained in classes how to do it

Found models for the laptop, bottle for the table, coca-cola bottle, humans, laptop and blue cube. Will write the code to spawn them in the right places.

**Comment by MarsRodrigues** [comment]
> > Its mandatory to create a script to spawn objects in the house. An example can be found in [this PSR repository](https://github.com/miguelriemoliveira/psr_23-24/blob/6b42eaa7925f1c7114a75c8d1acc46236f4a5613/Parte12/robutler_bringup_23-24/scripts/spawn_object.py) because it was explained in classes how to do it
> 
> Found models for the laptop, bottle for the table, coca-cola bottle, humans, laptop and blue cube. Will write the code to spawn them in the right places.

Trying to get all the coordinates for the spawn limits. It's taking a while, but will update the code as soon as possible.
